# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 21:44
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyetrackersession',
            name='cybertrustpath',
        ),
        migrations.RemoveField(
            model_name='eyetrackersession',
            name='password',
        ),
        migrations.RemoveField(
            model_name='eyetrackersession',
            name='username',
        ),
        migrations.AddField(
            model_name='eyetrackersession',
            name='args',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
        ),
    ]
