# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EyeTrackerSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('cybertrustpath', models.CharField(max_length=1000)),
            ],
        ),
    ]
